---
- name: Install Nexus
  hosts: all
  become: yes

  tasks:
    - name: Install Java
      yum:
        name: java-1.8.0-openjdk
        state: present

    - name: Download Nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/nexus-3.38.1-01-unix.tar.gz
        checksum: md5:d3d2e8ebef0816f412b66fe7a374f923
        dest: /opt/nexus3.tar.gz

    - name: Create workdir
      file:
        path: /opt/nexus
        state: directory

    - name: Unpack Nexus
      unarchive:
        src: /opt/nexus3.tar.gz
        dest: /opt/nexus/

    - name: Find last release
      find:
        file_type: directory
        patterns: 'nexus*'
        path: /opt/nexus
      register: nexus_path

    - name: Create nexus symlink
      file:
        path: /opt/nexus/nexus
        state: link
        src: "{{ nexus_path.files[0]['path'] }}"
      when: nexus_path.matched > 0

    - name: Copy environment file
      copy:
        src: nexus-server
        dest: /etc/default/nexus-server

    - name: Copy systemd file
      copy:
        src: nexus.service
        dest: /etc/systemd/system/nexus.service

    - name: Start Nexus service
      systemd:
        name: nexus
        enabled: yes
        state: started
      
    - name: Stop firewall
      systemd:
        name: firewalld
        enabled: no
        state: stopped
