---
- name: Master provision
  hosts: all

  tasks:
    - name: disable key check
      become: yes
      ini_file:
        path: /etc/ansible/ansible.cfg
        section: defaults
        option: host_key_checking
        value: False
     
    - name: Set alias ll
      replace:
        path: /home/vagrant/.bashrc
        regexp: "^#alias ll='ls -l'$"
        replace: "alias ll='ls -la'"
    
    - name: Set colors
      replace:
        path: /home/vagrant/.bashrc
        regexp: "^#force_color_prompt=yes$"
        replace: "force_color_prompt=yes"

    - name: install packages
      become: yes
      apt:
        pkg:
        - vim
        - mc
        - sshpass
        state: present

    - name: copy playbook
      copy:
        src: /vagrant/playbook.yaml
        dest: /home/vagrant/playbook.yaml

    - name: copy inventory
      copy:
        src: /vagrant/inventory
        dest: /home/vagrant/inventory

    - name: execute playbook
      shell: ansible-playbook -i /home/vagrant/inventory /home/vagrant/playbook.yaml | sed 's/\x1B\[[0-9;]\+[A-Za-z]//g'
      register: playbook_output
      changed_when: playbook_output.stdout_lines[-1] is regex("\schanged=[1-9]\d*\s")

    - debug: var=playbook_output.stdout_lines
